# Define Gitpod Configuration
tasks:
  - name: utils
    before: |
      sudo apt-get install tree
  - name: aws-cli
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

# Set environment variables globally
env:
  AWS_CLI_AUTO_PROMPT: "on-partial"
