#!/usr/bin/env bash

mkdir -p $OUTPUT_DIR



NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1;i<=$NUM_FILES;i++)); do

    # Generate a random filename
    FILENAME="$OUTPUT_DIR/file_$i.txt"

    # Generate random data and write it to the file

    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done